apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bmy1kPttTvltQ7dGOJqL2gJgE9lDUx+ITDC9WR8h31yrOcGJ2Kj3bOR5YddHbB5j93kRfpFA6QaDJlTPs5p2GP7p0OPcduzTf3BqIsBdaO4x1p6IraWmdoCGH/g5QDajbII2Ovj7oSUNWcDxEBSr5TVPUQGZE/9T76kcOfmSnchxbz0CWh1p0vtOkOToumghmmvd3ldzsL52ssKH7Lf4/ucf8ccaduxrsYV2af3fCyD/rR2d5qxlgs5eSgs48e73clWMrb7TsKIAybLN/PLZfoU6LFbI0GViGhKRJ04To5/QjcTqzir9Bo+SA1E=,iv:TYXdfQg55nfjIILy/uhzPc8p/4v484Oag9GSuiuoW1s=,tag:UAlOH9D4UFr2J8Dc6Px/BQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU2ZMVWY0K1kxaldVOFVT
            azFaRTVHOFFCZWl4dVpDTk5oMEpiYkJiV0dJCmdEZEJraFd5NWtybTAxVmpibkVY
            VkhZb3ViWU9KVC9sSUdCcm5iVGJtUUUKLS0tIEZENDJkbnJrb3VrbWpUZnNiYjY1
            ZUZuZytkeG5KUGtTS2dTbSszdXdaMGsKkCfqpHCcPpcP+lGPz+JvGuv0oQum5ket
            FLS7vy31o5B/mk9J2Yvxalb3YTNVEfwO8mROWw2W7f/h1kCM2ao6aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt8thvlstk0ulwrxpm7hvgcw9wnt0h9rgjed6htqscar27cj93fqq0f5yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:41:48Z"
    mac: ENC[AES256_GCM,data:MH9lyyan4/7ZRgBvO1yrQ2WNSnLJklN5TsjSKs6qdxcr5F+XgI2VMzYBiewVd4kOAOUK6+zcjtXXzt94mU/T5j8u5WXkOFS07jLUgEQ4HE3TC27Rrne4F95WS6GJ1EcoPYs1zQp0ipFQwvIAK2QtIHYpySgbjn0mRSiltVIXLsw=,iv:EzMYoGCLMBeVA6o5Et3iDtdUiw9BtedLfVlJ/q0lDqA=,tag:v7DPpGZ8MA3S/IgDC6D7CQ==,type:str]
    version: 3.13.3
