apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6aGAyxmA+SSBaxShbmjEnha1QKJFYqcR4tOg49W2pioHnoaqUjoxEIFQpNmv2nUc48+T0sc+W8AkfO9mPhE1Jqweg5yFM8lwH6cTJu2du0F7fI5X6Yd5yuNQflwyIX+ZUQBcys4f1G23BbhoUH0CnX3mHZNLuN9Ymzlz7+GrxBLoKfuDWKvsRtpTeZ80uIYY2KUZNXMLSTnE0gmdoAQhN5bOoA3u94NBSXCkLMh9MN6D10nkG8npB7MExwhU7lZevzUShNRYQLuxOeil77c3mlt1dJ+HGKTSLcC2uiDzkR9lGsEcW79M2Rer1Kk=,iv:CKurYvd4Ou/DGsVkCC9OwOSRAEhHzBsNbZBMKB9wuW4=,tag:81ApbbSrxEm64ooz/KZVuQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcUUvM0FWQUZjUFgwbjZP
            TXB2UEtkMjVtMWREUmRPYjJDRWJHOEw2VVZzCldxMS96bUltK0VNWDB4Szdjd2Ew
            RTlNYXpwV0w1am5ZdFIzWndISndQVlEKLS0tIGhiNG9mM3Z1Z0hMSnR6cVJlOTZr
            UXYwSENMTWFUeHZsK1BBck1uMkpRejgKDREyY1yGtQ3DDQudyESbBpWp4dwtdASN
            PqpqMLKy0wJKgiChPw0d3i+HtsaWA0psCRhJ69q0hZtNBcAmzzQdcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt8thvlstk0ulwrxpm7hvgcw9wnt0h9rgjed6htqscar27cj93fqq0f5yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:28:25Z"
    mac: ENC[AES256_GCM,data:bixLPCKSJZQw//XVd76wy11FHGarW83yORp+Agm7rvLmisdqi3F4ebRNkodfTrfTzyxsSxZm0ateZbgit3WRJUAOvZR7Ebbcpyq5p5M+tF+VPsoa7iG7icPuCPGSJDBJ6FIeb4A8rzU5MirWB638Bp8cG6KRY79yahXPSTgyCj4=,iv:fSoepZxp0O7KTJjunoRihp+G7J9wl9Ktsn4qal7Lh+s=,tag:ZlzFkyvavIinWG4Rj9ih/w==,type:str]
    version: 3.13.3
