apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZWyme2qgmQIZATdK,iv:kNUERlkQl7MtLipONJXQK++4cigs9K7El+k8mI5UDZ8=,tag:KHVswrpblC+QWPRN1+F2Pg==,type:str]
    user: ENC[AES256_GCM,data:R5iHuLjaCa8=,iv:J1GgWpiSoIQy3Xi2XynZAf/Q3B7BHa3xbem1+OKe9P0=,tag:NPvOGJPnODyGs4XYZDfBeQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q3FNNE1PaDVJMWx1K1VT
            YnkvRlo4YWRKbzBFeXgrc294ZlZxN2FuMlZZCjNtRm5kTTMzbk5NZXdGSGRjL0NI
            S3FyY3VXTnF4c1o2QVRjKzBNUldaOVEKLS0tIFFOYWR3YzlPN2xxSEkrWlVIT016
            MUl5amlwNWpQSUJ1U1hwVXRFZjlVTncKY8ZKNIi6lwDXob2P937OPD1yEtScf6bR
            YdZ2db5cBjDXmxHzcey2+O0x1lYSwy1O4sejCVjpkJ9wEVVcg7ubPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt8thvlstk0ulwrxpm7hvgcw9wnt0h9rgjed6htqscar27cj93fqq0f5yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T07:39:15Z"
    mac: ENC[AES256_GCM,data:NHmv5407Lgrceq6y5Tq/+Td1CiSHNqqIkZQZnM3lKxhFYFczzNpd86kGa+vYt3KYXbNgKMwIIf1nwQjhjNiL40erRV8P0qDVA0A4tKQIeSBCem2Zc58XmJqbfMzXq5g7UZmAsPR5H59CKC1Hyas+YYb8+Yscsd0nCy3z8Tqfpjs=,iv:h7ixp9A8kS362kaf6AQDUk7oQOWta6cOtxwJTG7qSFY=,tag:rU/ojFqULQF/gkiKqL0N3Q==,type:str]
    version: 3.13.3
