apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-app
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich 
      #  chart:
      #    spec:
      #      chart: immich 
      #      version: "3.2.2"
      #      sourceRef:
      #        kind: OCIRepository
      #        name: immich
      #      interval: 12h
        #  install:
        #    crds: Create
        #  upgrade:
        #    crds: CreateReplace
        #  driftDetection:
        #    mode: enabled

  values:
    server:
      controllers:
        main:
          containers:
            main:
              env:
                DB_HOSTNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: host
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: user
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: password
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: dbname

    valkey:
      enabled: true

    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc

            #  valuesFrom:
            #    - kind: ConfigMap
            #      name: immich-configmap
