#apiVersion: traefik.io/v1alpha1
#kind: Middleware
#metadata:
#  name: immich-limit-body-size
#spec:
#  buffering:
#    maxRequestBodyBytes: 0 
#---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: timeout-transport
spec:
  forwardingTimeouts:
    dialTimeout: 0s
    responseHeaderTimeout: 0s
    writeTimeout: 0s
    idleConnTimeout: 600s
