apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:C+Kwp6nMoLD1QNmNTGRJZY4nJtriu+5B4xsX/oVMmGNi7IOaN1rfXCsE2qyxt6OODRGjigr03ug=,iv:thDtEJH1pxdHNo/jVFWoGSrcWCGzNzdG3cRN4fJbqIM=,tag:gTXkzFCbhFOCDh/BkzPPiQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ25TUVU1bVFhS1l6Q29X
            ZllaVkZpT3JzclJHRlVuNjFyUW5xaUVTUlVRCmZNVWFPYXYwR0tMUGV1djNEUGNB
            WmxQdFF0SitqaEh6NHpNU25CaUJpQ00KLS0tIG1td1E4VWsvc3A2Nk5ZOGFnNTZP
            aWQ3bGFwNWsvQjRSb0lCYmIwRzlkS0kKM1J5C+V3g38cGEAtfkIRSZVUr/E5og/M
            wVya5Y8ism03BBIt8S++ijnhR8CI6m91vb88Y+g/o/SKwb0FgUSQFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt8thvlstk0ulwrxpm7hvgcw9wnt0h9rgjed6htqscar27cj93fqq0f5yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T14:41:41Z"
    mac: ENC[AES256_GCM,data:kW63d7zA2P8sVfZzuyuhVebWfAXLYMbYuhNeDcfgn1ssw4TfRR/CyhLlO5gzKf3kQQlwBa5EvsETDJLaOqn6OSeznFGBX1cQVLAzPzcefcDp3Kbs76HS08PFqvilXXkICPVWlSuzdtMS7/7IkXchYxQQ6AX/n67vxYYNMc36r8k=,iv:cfmM0dASm3R4h5mEWudQjSZPwI/ijgvP+SEduO09xBU=,tag:bRmHhtiMahS3tzY29I01Pw==,type:str]
    version: 3.13.3
